### ISSUE TITLE
zsh cheatsheet

### ISSUE THREAD

**Issue by exekutive** [ClementNerma/ClementNerma#1]
Doesn't work:
Access an array's element 	VARNAME[index]

I think the correct syntax is ${VARNAME[index]}
(index=1,2,3 ....)

**Comment by ClementNerma** [comment]
Hi,
Please comment on the thread directly instead of opening an issue on my personal repo ;)

**Comment by exekutive** [comment]
I couldn't find a way to do that

**Comment by ClementNerma** [comment]
You can't report issues *per se* on gists, but in the gist's page under the content you have a comments section.
